package com.proyecto.acs.pages;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.support.ui.ExpectedConditions;
import java.util.List;
import java.util.stream.Collectors;

public class PIMPage extends BasePage {

    private By addEmployeeTab = By.xpath("//a[text()='Add Employee']");
    private By employeeListTab = By.xpath("//a[text()='Employee List']");
    private By firstNameInput = By.name("firstName");
    private By lastNameInput = By.name("lastName");
    private By employeeIdInput = By.xpath("//label[text()='Employee Id']/../following-sibling::div/input");
    private By saveButton = By.cssSelector("button[type='submit']");
    private By requiredErrorMessage = By.xpath("//span[contains(@class, 'oxd-input-field-error-message')]");

    private By searchEmpNameInput = By.xpath("(//input[@placeholder='Type for hints...'])[1]");
    private By searchButton = By.cssSelector("button[type='submit']");
    private By noRecordsFoundText = By.xpath("//span[text()='No Records Found']");
    private By confirmDeleteButton = By.xpath("//button[contains(@class, 'oxd-button--label-danger')]");
    private By successToast = By.id("oxd-toaster_1");
    private By employeeRowCards = By.cssSelector(".oxd-table-row");

    public PIMPage(WebDriver driver) {
        super(driver);
    }

    public void goToAddEmployee() {
        click(addEmployeeTab);
    }

    public void goToEmployeeList() {
        click(employeeListTab);
    }

    public void fillEmployeeData(String firstName, String lastName) {
        type(firstNameInput, firstName);
        type(lastNameInput, lastName);
    }

    public void fillFirstName(String firstName) {
        type(firstNameInput, firstName);
    }

    public void fillLastName(String lastName) {
        type(lastNameInput, lastName);
    }

    public void clickSave() {
        click(saveButton);
    }

    public String getEmployeeId() {
        return find(employeeIdInput).getAttribute("value"); // Obtiene el valor autogenerado
    }

    public void searchEmployeeByName(String name) {
        type(searchEmpNameInput, name);
        click(searchButton);
    }

    public int getVisibleEmployeeRowCount() {
        return findAll(employeeRowCards).size();
    }

    public List<String> getVisibleEmployeeRowTexts() {
        return findAll(employeeRowCards).stream().map(WebElement::getText).collect(Collectors.toList());
    }

    public void waitForEmployeeRowContaining(String expectedText) {
        By rowContainingText = By.xpath("//div[contains(@class, 'oxd-table-row') and contains(., '" + expectedText + "')]");
        wait.until(ExpectedConditions.presenceOfElementLocated(rowContainingText));
    }

    public boolean isEmployeeRowContainingVisible(String expectedText) {
        By rowContainingText = By.xpath("//div[contains(@class, 'oxd-table-row') and contains(., '" + expectedText + "')]");
        return isDisplayed(rowContainingText);
    }

    public void deleteFirstEmployeeInList() {
        List<WebElement> rows = findAll(employeeRowCards);
        if (rows.isEmpty()) {
            throw new IllegalStateException("No hay filas visibles para eliminar.");
        }

        rows.get(0).findElement(By.xpath(".//button[contains(@class, 'oxd-icon-button')][last()]")).click();
        click(confirmDeleteButton);
    }

    public void deleteEmployeeByName(String employeeName) {
        By deleteButton = By.xpath("//div[contains(@class, 'oxd-table-row') and contains(., '" + employeeName + "')]//button[contains(@class, 'oxd-icon-button')][last()]");
        click(deleteButton);
        click(confirmDeleteButton);
    }

    public void openFirstVisibleEmployee() {
        List<WebElement> rows = findAll(employeeRowCards);
        if (!rows.isEmpty()) {
            rows.get(0).click();
        }
    }

    public boolean isRequiredMessageDisplayed() {
        return isDisplayed(requiredErrorMessage);
    }

    public boolean isNoRecordsFoundDisplayed() {
        return isDisplayed(noRecordsFoundText);
    }

    public boolean isSuccessToastDisplayed() {
        return isDisplayed(successToast);
    }

    public boolean isEmployeeIdAutoGenerated() {
        String employeeId = getEmployeeId();
        return employeeId != null && !employeeId.isBlank() && employeeId.matches("\\d+");
    }

    public boolean isOnPersonalDetailsPage() {
        return wait.until(ExpectedConditions.urlContains("/pim/viewPersonalDetails/empNumber/"));
    }
}