package com.proyecto.acs.tests;

import com.proyecto.acs.base.BaseTest;
import com.proyecto.acs.pages.LoginPage;
import com.proyecto.acs.pages.MenuPage;
import com.proyecto.acs.pages.PIMPage;
import org.testng.Assert;
import org.testng.annotations.Test;

public class PIMTest extends BaseTest {

    private PIMPage openEmployeeList() {
        LoginPage loginPage = new LoginPage(driver);
        MenuPage menu = loginPage.loginAs("Admin", "admin123");
        return menu.clickPimMenu();
    }

    @Test(description = "TC-07: Agregar nuevo empleado con campos obligatorios")
    public void tc07_AddEmployeeWithRequiredFields() {
        PIMPage pimPage = openEmployeeList();
        pimPage.goToAddEmployee();

        pimPage.fillEmployeeData("Pedro", "Aragon");
        pimPage.clickSave();

        Assert.assertTrue(pimPage.isOnPersonalDetailsPage(), "El empleado no se guardó correctamente ni redirigió a detalles personales.");
    }

    @Test(description = "TC-08: Intentar guardar empleado sin apellido")
    public void tc08_SaveEmployeeWithoutLastName() {
        PIMPage pimPage = openEmployeeList();
        pimPage.goToAddEmployee();
        pimPage.fillFirstName("Jose");
        pimPage.clickSave();

        Assert.assertTrue(pimPage.isRequiredMessageDisplayed(), "No se mostró la validación requerida para el apellido.");
    }

    @Test(description = "TC-09: Buscar empleado existente por nombre en la lista PIM")
    public void tc09_SearchExistingEmployeeByName() {
        PIMPage pimPage = openEmployeeList();
        pimPage.goToAddEmployee();
        pimPage.goToEmployeeList();
        pimPage.searchEmployeeByName("Amelia");

        Assert.assertTrue(pimPage.getVisibleEmployeeRowCount() > 0, "La búsqueda no devolvió registros visibles.");
        pimPage.waitForEmployeeRowContaining("Amelia");
        Assert.assertTrue(pimPage.isEmployeeRowContainingVisible("Amelia"), "Los registros encontrados no corresponden al empleado buscado.");
    }

    @Test(description = "TC-10: Buscar empleado inexistente")
    public void tc10_SearchNonexistentEmployee() {
        PIMPage pimPage = openEmployeeList();
        pimPage.goToEmployeeList();
        pimPage.searchEmployeeByName("asdf");

        Assert.assertTrue(pimPage.isNoRecordsFoundDisplayed(), "El sistema no mostró 'No Records Found' para un empleado inexistente.");
    }

    @Test(description = "TC-11: Eliminar un empleado existente de la lista")
    public void tc11_DeleteExistingEmployee() {
        PIMPage pimPage = openEmployeeList();
        pimPage.goToEmployeeList();
        pimPage.searchEmployeeByName("Amelia");
        pimPage.waitForEmployeeRowContaining("Amelia");
        pimPage.deleteEmployeeByName("Amelia");

        Assert.assertTrue(pimPage.isSuccessToastDisplayed(), "No se mostró la notificación de éxito al eliminar el empleado.");

        pimPage.searchEmployeeByName("Amelia");
        Assert.assertTrue(pimPage.isNoRecordsFoundDisplayed(), "El empleado eliminado sigue apareciendo en la lista de empleados.");
    }

    @Test(description = "TC-14: Validación del formato del campo ID de Empleado")
    public void tc14_VerifyEmployeeIdAutoGenerated() {
        PIMPage pimPage = openEmployeeList();
        pimPage.goToAddEmployee();

        Assert.assertTrue(pimPage.isEmployeeIdAutoGenerated(), "El Employee Id no fue autogenerado con formato numérico.");
    }
}
